// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoZe8Ueb-DxFA_BJ0l1lPGS8BXrLnrvVo',
    appId: '1:662912161699:web:7cd160a1ffe0c1ddc56c16',
    messagingSenderId: '662912161699',
    projectId: 'triplanka-6043b',
    authDomain: 'triplanka-6043b.firebaseapp.com',
    storageBucket: 'triplanka-6043b.firebasestorage.app',
    measurementId: 'G-YFVL0XQPHW',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkfs5nqWSf_mGNN7yz4Vh_gXGsMh0SRSA',
    appId: '1:662912161699:android:b7d5b0c323657b3ac56c16',
    messagingSenderId: '662912161699',
    projectId: 'triplanka-6043b',
    storageBucket: 'triplanka-6043b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhysl-2wrPKUsojFpe4Sek3sCWhFHIBTA',
    appId: '1:662912161699:ios:4bd0fcc3c7b7fff2c56c16',
    messagingSenderId: '662912161699',
    projectId: 'triplanka-6043b',
    storageBucket: 'triplanka-6043b.firebasestorage.app',
    iosBundleId: 'com.example.triplanka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhysl-2wrPKUsojFpe4Sek3sCWhFHIBTA',
    appId: '1:662912161699:ios:4bd0fcc3c7b7fff2c56c16',
    messagingSenderId: '662912161699',
    projectId: 'triplanka-6043b',
    storageBucket: 'triplanka-6043b.firebasestorage.app',
    iosBundleId: 'com.example.triplanka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoZe8Ueb-DxFA_BJ0l1lPGS8BXrLnrvVo',
    appId: '1:662912161699:web:74431b4a97baaee2c56c16',
    messagingSenderId: '662912161699',
    projectId: 'triplanka-6043b',
    authDomain: 'triplanka-6043b.firebaseapp.com',
    storageBucket: 'triplanka-6043b.firebasestorage.app',
    measurementId: 'G-QX03GF5BKZ',
  );
}
